version: '3.4'

services:

  sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:1433" 

  todos-api:
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal, 5433;Database=TodoDb;User Id=sa;Password=${DB_PASSWORD}
      - CreateMockData=N
    ports:
      - "5101:80"

  frontend-spa:
    environment:
      - API_URL=http://localhost:5101
    ports:
      - "5100:80"

